redisclient: redisclient.cpp
		g++ -o redisclient redisclient.cpp -std=c++14 -L/data/opt/course/redis/redis-3.2.4/deps/hiredis/ -I/data/opt/course/redis/redis-3.2.4/deps/hiredis/ -lhiredis -g3

clean: 
		rm redisclient

.PHONY: clean 
