redisclient: redisclient.cpp
		g++ -o redisclient redisclient.cpp -std=c++14 -L/home/1155081867/development/redis-3.2.4/deps/hiredis -I/home/1155081867/development/redis-3.2.4/deps -lhiredis -g3

clean: 
		rm redisclient

.PHONY: clean 
